### ISSUE TITLE
Updated metadata shows as unknown for delegators

### ISSUE THREAD

**Issue by digitalassetnews** [Emurgo/yoroi-frontend#2010]
Metadata was updated for the below pool ids, metadata hash is correct. However existing delegators in yoroi see the pool as unknown in their delegation center. 

727ceb44ef548cbb6f36d7023dfbd8400d48aea0c84b675beff1dd12
9b97ad981c8456110e17b1297a58961147209b7dc0d8e78b44ed8bcb

**Comment by SebastienGllmt** [comment]
Usually this updates after a few hours

**Comment by digitalassetnews** [comment]
> Usually this updates after a few hours

in this case its been over a week and delegators are still reporting the issue, similar reports from other SPO's as well who have also recently updated description.

**Comment by SebastienGllmt** [comment]
Usually pools who bring up an "unknown pool" issue have the issue already auto-resolved by the time we look into it.

Usually if you have no issues flagged on https://pool.vet/ then Yoroi will update to reflect your pool after a few hours. I've never heard of it taking more than a few hours, but maybe the issues your pools get on pool.vet is related (I'm not sure if SMASH checks for whether or not the relay nodes can be reached)

**Comment by brouwerQ** [comment]
I have the same issue. If I search my pool in delegation list, the name shows up fine, but on the dashboard it says 'Unknown pool'. The same issue in the mobile wallet. It has been a few days now, so the few hours have long passed...
Also, nor another block explorer, nor Daedalus show any issues.

**Comment by brouwerQ** [comment]
I've changed to pool to which I delegated a few times and it seems to happen with 'small' pools.

EDIT now everything is looking ok for my pool

**Comment by fmcatalan** [comment]
Hi, this is our second epoch as a pool, and still appears as Unknown. At some point I saw it right, but after a delegator asked me what was going on, I re checked and there was the Unknown again... Pool.vet and adapools show the right info, only in yoroi it gets scrambled
[https://puu.sh/HvHkh/28984a2a8a.png](url)
Pool id: 6658af81937bd21017801fc1b89e2d26af75d358a71bbdc40e1907b5
On Adapools.io: [https://puu.sh/HvHp3/046a38db16.png](url)

**Comment by SebastienGllmt** [comment]
@fmcatalan I tried your pool and it loads the pool information fine for me. Are you still having issues?

**Comment by fmcatalan** [comment]
Yes, I guess with 259 It got sorted? in 258 it was still Unknown. Thanks for checking it!

**Comment by Straightpool** [comment]
I have the same issue in my pool, I created a properly documented issue here:  https://github.com/Emurgo/yoroi-frontend/issues/2164

**Comment by nakyll** [comment]
Same here....

**Comment by woodland-ada-pools** [comment]
Same issue here as well for our pool ASPEN. The pool appears correctly if you search for it in the delegation list, but if you delegate it appears as UNKNOWN_POOL. This has been going on for about 3 days now.

**Comment by jarstorm** [comment]
Hello, and thank you for your contribution.
We're currently reviewing long-standing issues to keep the tracker manageable. As this issue hasn't seen activity in some time, we're closing it.
If the problem persists or you'd like to follow up, feel free to comment and we'll reopen it.
