### ISSUE TITLE
"Change address payment credential is a path" message on Trezor device

### ISSUE THREAD

**Issue by forgiSL** [Emurgo/yoroi-frontend#2575]
This message appears on the device when user is trying to send a transaction after staking.

Trezor FW: 2.4.3.

To reproduce:

1. Start a Trezor up on Yoroi 
2. Transfer 100 ADA into it in a single UTXO
3. Stake the 100ADA somewhere
4. Attempt to send 1 ADA to another wallet
5. You should see all these messages asking where to send change, confirm stake credentials etc.

**Comment by guideras** [comment]
I'm trying it, but apparently i'm having to confirm to each of the assets in my wallet, should i do that? I'm a little worried, I have more than 110 assets (nfts) in the wallet. @forgiSL

**Comment by JaimeToca** [comment]
Hello everyone ! I'm facing the same issue :/ 

 I get "change adress payment credential is a path:" With some kid of path "M/..." I approve it and then I get

"change adress stake credential is a key hash:" with an adress, not the same I am sending to. At this point Trezor Model T displays a red X.

**Comment by matejcik** [comment]
My guess is that Yoroi is providing the staking address as a literal instead of a path.

In order to skip this warning, [the following conditions](https://github.com/trezor/trezor-firmware/blob/572f3eda20960325d353930b7b32220eec8f0c93/core/src/apps/cardano/helpers/credential.py#L199-L209) must be met on all change outputs:

1. the address type is `BASE`
2. the derivation path `address_n` matches schema `m/1852'/1815'/account'/change/address`
3. the derivation path **`address_n_staking` is `m/1852'/1815'/account'/2/0` for the same account**
4. `staking_key_hash` is unset -- it should _only_ be used if the address is staking outside Trezor's control

Let me know if you need more info / help.

**Comment by matejcik** [comment]
also maybe some part of this is magically resolved in Trezor Connect, so upgrading Connect should be the first step

**Comment by blackhat2020** [comment]
Hi everyone,
I have the same issue as described above
I get "change address payment credential is a path" in both situations when I am trying to claim my rewards and when I am trying to transfer ADA to another Yoroi wallet not connected with Trezor.

do you have an ETA when it will be fixed ?

**Comment by zuzunker** [comment]
> Hi everyone, I have the same issue as described above I get "change address payment credential is a path" in both situations when I am trying to claim my rewards and when I am trying to transfer ADA to another Yoroi wallet not connected with Trezor.
> 
> do you have an ETA when it will be fixed ?

Hi, @blackhat2020 , which version of the extension are you using at the moment where you have the issue?

**Comment by JaimeToca** [comment]
4.9.4 Yoroi and Trezor 2.4.3, I'm still having this issue :( @vsubhuman

**Comment by blackhat2020** [comment]
Current version: 4.9.4
Trezor current firmware version is 2.4.3

**Comment by blackhat2020** [comment]
> > Hi everyone, I have the same issue as described above I get "change address payment credential is a path" in both situations when I am trying to claim my rewards and when I am trying to transfer ADA to another Yoroi wallet not connected with Trezor.
> > do you have an ETA when it will be fixed ?
> 
> Hi, @blackhat2020 , which version of the extension are you using at the moment where you have the issue?

Yoroi Current version: 4.9.4
Trezor current firmware version is 2.4.3

**Comment by Alfred978** [comment]
Hello @matejcik @vsubhuman @yushih , I have recently updated my Trezor to version 2.4.3 and when I try to send ADA to another wallet I get the message "change address payment credential is a path". 

I see the issue was open in mid December....  Any news regarding this problem? Any plan to fix it?

Thanks a lot !!
Cheers,
